# Generated by Django 3.1.4 on 2021-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210111_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
