# Generated by Django 3.1.4 on 2021-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210115_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='alumno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='amigo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='profesor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
