# Generated by Django 3.1.4 on 2021-01-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210120_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='alumno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='profesor',
            field=models.BooleanField(default=False),
        ),
    ]
