# Generated by Django 3.1.4 on 2021-01-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210103_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='core'),
        ),
    ]
