# Generated by Django 3.1.4 on 2021-01-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210103_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.CharField(default='profesor', max_length=30),
            preserve_default=False,
        ),
    ]
