# Generated by Django 3.1.4 on 2021-01-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
