# Generated by Django 3.1.4 on 2021-01-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210110_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
