# Generated by Django 3.1.4 on 2021-01-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prerequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.TextField()),
                ('nivel', models.CharField(default='m', max_length=1)),
            ],
        ),
    ]
