# Generated by Django 3.1.4 on 2021-01-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0002_prerequisito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prerequisito',
            new_name='recomendacion',
        ),
    ]
