# Generated by Django 3.1.4 on 2021-01-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210128_1942'),
        ('visitante', '0003_auto_20210130_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
            preserve_default=False,
        ),
    ]
