# Generated by Django 3.1.4 on 2021-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0004_recomendacion_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='nivel',
            field=models.CharField(default='m', max_length=10),
        ),
    ]
