# Generated by Django 3.1.4 on 2021-01-31 19:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_media'),
        ('visitante', '0005_auto_20210130_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
    ]
