# Generated by Django 3.1.4 on 2021-02-01 20:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0006_capitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitante.capitulo')),
            ],
        ),
    ]
