# Generated by Django 3.1.4 on 2021-02-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0007_tema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='curso',
            new_name='capitulo',
        ),
    ]
