# Generated by Django 3.1.4 on 2021-02-02 02:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0008_auto_20210201_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(default='Texto', max_length=10)),
                ('dirurl', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='core')),
                ('media', models.FileField(blank=True, null=True, upload_to='visitante')),
                ('texto', ckeditor.fields.RichTextField()),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitante.tema')),
            ],
        ),
    ]
