# Generated by Django 3.1.4 on 2021-02-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0009_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='detalle',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
