# Generated by Django 3.1.4 on 2021-02-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0011_auto_20210202_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='nombrearchivo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
