# Generated by Django 3.1.4 on 2021-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0012_detalle_nombrearchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='tipoarchivo',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
