# Generated by Django 3.1.4 on 2021-02-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0013_detalle_tipoarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='referencia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
