# Generated by Django 3.1.4 on 2021-02-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0014_detalle_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
