# Generated by Django 3.1.4 on 2021-02-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0015_auto_20210209_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle',
            old_name='referencia',
            new_name='referencia_imagen',
        ),
        migrations.AddField(
            model_name='detalle',
            name='referencia_media',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalle',
            name='referencia_texto',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
